// <auto-generated />
using System;
using Cars.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cars.Model.Migrations
{
    [DbContext(typeof(CarsContext))]
    partial class CarsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Cars.Model.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category")
                        .HasMaxLength(7);

                    b.Property<byte?>("Cyl");

                    b.Property<short?>("HP");

                    b.Property<string>("Hyperlink")
                        .HasMaxLength(50);

                    b.Property<double?>("Liter");

                    b.Property<byte?>("MPG_City");

                    b.Property<byte?>("MPG_Highway");

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.Property<string>("Trademark")
                        .HasMaxLength(50);

                    b.Property<string>("TransmissAutomatic")
                        .HasMaxLength(3);

                    b.Property<byte?>("TransmissSpeedCount");

                    b.HasKey("ID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Cars.Model.CarScheduling", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AllDay");

                    b.Property<int?>("CarId");

                    b.Property<string>("ContactInfo");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EndTime");

                    b.Property<int?>("EventType");

                    b.Property<int?>("Label");

                    b.Property<string>("Location")
                        .HasMaxLength(50);

                    b.Property<decimal?>("Price")
                        .HasColumnType("smallmoney");

                    b.Property<string>("PatternId");

                    b.Property<string>("RecurrenceRule");

                    b.Property<string>("RecurrenceIndex");

                    b.Property<string>("ReminderInfo");

                    b.Property<DateTime?>("StartTime");

                    b.Property<int?>("Status");

                    b.Property<string>("Subject")
                        .HasMaxLength(50);

                    b.Property<int?>("UserId");

                    b.HasKey("ID");

                    b.ToTable("CarScheduling");
                });
#pragma warning restore 612, 618
        }
    }
}
